Adds Info and Debug logger functionality
paketo-buildpacks/packit pull request #254
Opened 2021-11-17 21:54 UTC by ForestEckhardt

Resolves #252 

## Checklist

* [x] I have viewed, signed, and submitted the Contributor License Agreement.
* [x] I have linked issue(s) that this PR should close using keywords or the Github UI (See [docs](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue))
* [x] I have added an integration test, if necessary.
* [x] I have reviewed the [styleguide](https://github.com/paketo-buildpacks/community/blob/main/STYLEGUIDE.md) for guidance on my code quality.
* [x] I'm happy with the commit history on this PR (I have rebased/squashed as needed).

2021-11-18 15:30 UTC, fg-j commented
This is awesome. Could you add some godoc examples of how a buildpack author can incorporate this logger into their buildpack in practice? The tests sort of show it, but a direct example would be great.

2021-11-18 15:48 UTC, ForestEckhardt commented
For sure I could doc up the whole package if that is something we are looking for!

2021-11-18 16:06 UTC, ryanmoran commented
There's quite a bit of duplication happening here. We've now got 3 different loggers with duplicative implementation APIs and switching logic. I think we can achieve something a bit simpler by just controlling whether or not the writer goes somewhere or is discarded. I've thrown together a simplified example here: https://github.com/paketo-buildpacks/packit/blob/log-levels-alt/scribe/logger.go

Take a look and let me know what you think.

2021-11-18 21:51 UTC, ForestEckhardt commented
Moving this to draft until I have the examples written up!

2021-11-29 16:09 UTC, ForestEckhardt commented
@fg-j @ryanmoran Alrighty took me a little longer than I thought but the docs are up and running. Couple call outs.
- Ryan and I have decided to deprecate the Bar object as it is not fully implemented and we do not foresee it being used in the near future and and we are going to use it we would like to overhaul the interface.
- I could not get a tested example working for the Color object because of that I also do not put together examples for the writer. I could make an indented writer but it did not seem completely necessary to me to set up examples. If you would like an example just let me know.
- I just put together the best blurb that I could for the top level description I am more than happy to get feedback on this one.

Hope this accomplishes everything that y'all are looking for.

2021-11-29 16:32 UTC, fg-j requested changes
Maybe I didn't understand your comment @ForestEckhardt about getting a working example with Color, but if possible I'd love to see an example of how to properly use the logger with Debug functionality.

2021-11-29 16:32 UTC, fg-j commented on scribe/logger.go
> +// logging task as well as debug logging.
```suggestion
// logging tasks as well as debug logging.
```

2021-11-29 16:32 UTC, fg-j commented on scribe/logger.go
> +// NewLogger take a writer and return a Logger that writes to the given
```suggestion
// NewLogger takes a writer and returns a Logger that writes to the given
```

2021-11-29 16:32 UTC, fg-j commented on scribe/scribe.go
> +// own functionality using atomic peices.
```suggestion
// own functionality using atomic pieces.
```

2021-11-29 16:32 UTC, fg-j commented on scribe/writer.go
> +// WithColor take a Color and returns an Option which can be passed in while
```suggestion
// WithColor takes a Color and returns an Option which can be passed in while
```

2021-11-29 16:33 UTC, fg-j commented on scribe/logger.go
> +// logger. To enable debug logging the log level must be set to "DEFAULT".
^^ If `DEFAULT` is in fact the correct word, then this docstring confused me!

2021-11-29 16:37 UTC, ForestEckhardt commented on scribe/logger.go
> +// logger. To enable debug logging the log level must be set to "DEFAULT".
Whoops

2021-11-29 16:40 UTC, ForestEckhardt commented
> Maybe I didn't understand your comment @ForestEckhardt about getting a working example with Color, but if possible I'd love to see an example of how to properly use the logger with Debug functionality.

My trouble with Color is that the only way I know haw to test the examples is by testing the contents of stdout. The Colors function adds a prefix and a suffix that is interpreted by the terminal and changes the display but seemingly does not make it to standard out. If there is another way of getting the examples working and testing it I am game!

I totally forgot that was the feature I added to start this work 🤦  I will add an example ASAP!

2021-11-29 18:44 UTC, ForestEckhardt commented
@fg-j So after so discussion with @ryanmoran and a little investigating on his part he discovered that: 
> The terminal escape sequences are dropped if the output is not a TTY, and the io.Pipe that the Examples feature uses is not a TTY. 

So it would appear that it is not possible to test the Color functionality using the Go Examples testing framework. I hope that clears things up.

2021-12-02 18:48 UTC, fg-j approved these changes
Thanks for adding that debug logging example. LGTM!

2021-12-02 18:52 UTC, ryanmoran commented on scribe/logger.go
> +	switch level {
```suggestion
	switch strings.ToUpper(level) {
```

2021-12-02 19:45 UTC, ryanmoran approved these changes

2021-12-02 20:26 UTC, fg-j approved these changes

2021-12-02 20:26 UTC, merged