Enable architecture specific dependencies
paketo-buildpacks/packit pull request #622
Opened 2024-12-20 15:28 UTC by c0d1ngm0nk3y

fixes https://github.com/paketo-buildpacks/packit/issues/618

## Summary

When looking for an dependency, the architecture is taken into account. The default architecture (if not provided by a dependency is "amd64" to ensure backwards compatibility. The architecture to look for is taken from the system or an env variable `BP_ARCH` to enable unit testing. 

## Use Cases

Dependencies for several architectures (e.g. "arm" and "amd64")

## Checklist

* [X] I have viewed, signed, and submitted the Contributor License Agreement.
* [X] I have linked issue(s) that this PR should close using keywords or the Github UI (See [docs](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue))
* [ ] I have added an integration test, if necessary.
* [X] I have reviewed the [styleguide](https://github.com/paketo-buildpacks/community/blob/main/STYLEGUIDE.md) for guidance on my code quality.
* [X] I'm happy with the commit history on this PR (I have rebased/squashed as needed).

2025-01-17 14:06 UTC, c0d1ngm0nk3y commented
@paketo-buildpacks/tooling-maintainers Could someone have a look? That is a prerequisite for supporting multiarch in paketo-buildpacks/nodejs.

2025-01-23 14:53 UTC, ForestEckhardt approved these changes

2025-01-23 14:54 UTC, ForestEckhardt commented
Could you please rebase this PR so I can merge it in!

2025-01-24 13:24 UTC, pacostas requested changes

2025-01-24 13:24 UTC, pacostas commented on postal/buildpack.go
> +	Arch string `toml:"arch"`
There are several platforms, for example, pack cli has plenty of them when it comes to build and image https://github.com/buildpacks/pack/blob/5cca9c51a61cf1bb8b0b6ba479bbbf10a65f0377/internal/target/platform.go#L31-L47 For nodejs we have a subset of them https://github.com/nodejs/node/blob/main/BUILDING.md#platform-list which I think it would be good to start with. So my suggestion on this one would be to also add another variable called `OS` or `operating-system` which will indicate the operating system of the dependency

2025-01-24 13:24 UTC, pacostas commented on postal/service.go
>  		strings.Join(e.supportedVersions, ", "),
Same on this one we should add the os attribute

2025-01-24 13:24 UTC, pacostas commented on postal/service_test.go
> +		Expect(os.Setenv("BP_ARCH", "amd64")).To(Succeed())
On this one, instead of having BP_ARCH and BP_OS, we could rename the `BP_ARCH` to something like BP_PLATFORM or BP_TARGET, which will include both architecture and operating system, similar to what pack cli does with the targets.

2025-01-24 13:24 UTC, pacostas commented on postal/service.go
> +func archFromSystem() string {
In terms of clean code, one function should only do one thing, I would remove from this function, the two things that is doing 1. looking if the environment variable exists 2. fetching the system architecture. Changing that function to fetching only the architecture does not make sense as there is already a function for that. Therefore, I would suggest to move this logic out in to the Parent function (`Resolve`) as I think this is totally normal as there is already logic for validating other things like (`dependency version` and `stacks`). Althouh, if you decide to fetch the platform, then it would be good to wrap these two lines in a function called `getSystemPlatform` as it will be more than one line (one for fetching the `GOARCH` and one for fetching the `GOOS`

2025-01-24 13:24 UTC, pacostas commented on postal/service.go
> +func archFromSystem() string {
I think we dont want to default into the system that the user is using as pack currently fallbacks to linux/amd64, so I would choose this platform as default, in order to avoid any errors from macos users that currently building applications

2025-01-31 13:17 UTC, c0d1ngm0nk3y commented on postal/service.go
> +func archFromSystem() string {
> I think we dont want to default into the system

I might be completely wrong, but that is not what is done. It looks up the architecture of the runtime, meaning the buildpack that actually called `getDependency()`. So no other architecture could even work. The `BP_ARCH` is only needed for unit tests.

I tried to keep everything as similar to [`libak`](https://github.com/paketo-buildpacks/libpak/blob/aa7107c9e10714dce0adc2a13d85aa26cd739253/buildpack.go#L566) as possible.

2025-01-31 13:21 UTC, c0d1ngm0nk3y commented on postal/buildpack.go
> +	Arch string `toml:"arch"`
I am no expert on the whole multiarch thing, but `operating-system` would be wrong, wouldn't it? The operating system is for all dependencies `linux` - it is the same run image after all. We "only" have to differ dependencies for the architecture of the image. So I thing anything other than `Arch` would be quite confusing, don't you think?

2025-01-31 13:24 UTC, c0d1ngm0nk3y commented
> Could you please rebase this PR so I can merge it in!

I will update, but wait a bit with the merge so that @pacostas can respond to the comments.

2025-01-31 13:59 UTC, pacostas commented on postal/buildpack.go
> +	Arch string `toml:"arch"`
I thought that we might need to support generating images for macos, but currently there is no such use case so makes sense to not over-complicate it. LGTM

2025-01-31 13:59 UTC, pacostas commented on postal/service.go
>  		strings.Join(e.supportedVersions, ", "),
If we dont use the os, this comment does not apply.

2025-01-31 14:00 UTC, pacostas commented on postal/service.go
> +func archFromSystem() string {
I see, so seems that it is not breaking the default behavior. LGTM

2025-01-31 14:00 UTC, pacostas commented on postal/service_test.go
> +		Expect(os.Setenv("BP_ARCH", "amd64")).To(Succeed())
If we dont use the os, this comment does not apply.

2025-01-31 14:00 UTC, pacostas commented
> > Could you please rebase this PR so I can merge it in!
> 
> I will update, but wait a bit with the merge so that @pacostas can respond to the comments.

LGTM

2025-02-14 09:34 UTC, c0d1ngm0nk3y commented
@ForestEckhardt Would you merge it?

2025-03-05 15:11 UTC, merged